/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eepromprogrammer_SerialPortInterface */

#ifndef _Included_eepromprogrammer_SerialPortInterface
#define _Included_eepromprogrammer_SerialPortInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    portNameValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_eepromprogrammer_SerialPortInterface_portNameValid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    firstPortAvailable
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eepromprogrammer_SerialPortInterface_firstPortAvailable
  (JNIEnv *, jobject);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    writeToPort
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_eepromprogrammer_SerialPortInterface_writeToPort
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setBaudRate
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setBaudRate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setStopBits
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setStopBits
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setByteSize
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setByteSize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    nativeSetParity
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_nativeSetParity
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setParityOn
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setParityOn
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setOutXCTSDSR
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setOutXCTSDSR
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setDTRControl
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setDTRControl
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    setDiscardNull
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_eepromprogrammer_SerialPortInterface_setDiscardNull
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
