/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eepromprogrammer_SerialPortInterface */

#ifndef _Included_eepromprogrammer_SerialPortInterface
#define _Included_eepromprogrammer_SerialPortInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eepromprogrammer_SerialPortInterface
 * Method:    portNameValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_eepromprogrammer_SerialPortInterface_portNameValid
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
